version: '3.9'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - ./apps/api/.env
  db_test:
    image: postgres
    container_name: db_test
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
